// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvM8wr9icDn7UsvknQeFH_OKcA0gp81_I',
    appId: '1:678717948367:web:b9f742b7beee34c9bf92ba',
    messagingSenderId: '678717948367',
    projectId: 'renomate-48df7',
    authDomain: 'renomate-48df7.firebaseapp.com',
    storageBucket: 'renomate-48df7.appspot.com',
    measurementId: 'G-ZBBRM6NR6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQMOTCKky-Jggo34CY49hCDtRDppY04s',
    appId: '1:678717948367:android:ee785d895cbe29d4bf92ba',
    messagingSenderId: '678717948367',
    projectId: 'renomate-48df7',
    storageBucket: 'renomate-48df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAnztbPfJK5kMxgWc7C8CwE0rzamoKHyQ',
    appId: '1:678717948367:ios:b214fb1d85ab0dc0bf92ba',
    messagingSenderId: '678717948367',
    projectId: 'renomate-48df7',
    storageBucket: 'renomate-48df7.appspot.com',
    iosBundleId: 'com.example.RenoMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAnztbPfJK5kMxgWc7C8CwE0rzamoKHyQ',
    appId: '1:678717948367:ios:c66badb6735a1766bf92ba',
    messagingSenderId: '678717948367',
    projectId: 'renomate-48df7',
    storageBucket: 'renomate-48df7.appspot.com',
    iosBundleId: 'com.example.RenoMate.RunnerTests',
  );
}
